### ISSUE TITLE
Oprava úkolu

### ISSUE THREAD

**Issue by jakubledl** [HedvikaCapkova/Czechitas_ukol_lekce_5#1]
Ahoj!

Parádní práce, řešení se mi moc líbí, třeba použití ternárního operátoru v komponentě :-) Bohužel je tam jedna věc, kvůli které to ještě nemůžu schválit: podle bodu g. v zadání (a Martinových obecných pokynů) má filtrování všech / jenom nedokončených úkolů probíhat na API, tj. API samotné musíme zavolat na adrese, která nám rovnou vrátí ty správné úkoly; fetchnout všechno a pak to filtrovat na klientovi není bohužel správné řešení.

Tak jen tuhle drobnost opravit a bude to super :-)

**Comment by HedvikaCapkova** [comment]
Ahoj, opraveno 🙂

**Comment by jakubledl** [comment]
Absolutní pecka 🥇
